### ISSUE TITLE
selfhost

### ISSUE THREAD

**Issue by CodeMeZone** [TTV-LOL/extensions#1]
We all know that sooner or later twitch is going to stop this, can show us how to self-host it?

**Comment by swiftaes** [comment]
This would be pretty nice but I'm not sure if they'll want to share the server side code

**Comment by CodeMeZone** [comment]
> This would be pretty nice but I'm not sure if they'll want to share the server side code

Worth a try, I'm sure someone will sooner or later.

**Comment by revunix** [comment]
yeah please release server source code.

okay, found it: https://github.com/pixeltris/TwitchAdSolutions/tree/master/proxy

**Comment by captainswain** [comment]
We are still ironing out some bugs on our end proxy server-wise, so I think we are currently holding off on releasing the code until we have a chance to clean it up & verify that it is 100% functional.

**Comment by swiftaes** [comment]
> We are still ironing out some bugs on our end proxy server-wise, so I think we are currently holding off on releasing the code until we have a chance to clean it up & verify that it is 100% functional.

Oh wow never though it would get released. Cannot wait until then :)

**Comment by cookie-monster-bit** [comment]
Any update to this?

**Comment by CodeMeZone** [comment]
> Any update to this?

Nope, I hope tho.
