### ISSUE TITLE
There was a network error. Please try again. (Error #2000)

### ISSUE THREAD

**Issue by ghost** [TTV-LOL/extensions#13]
Ever since I started using TTV-LOL I started seeing this error code with some streams. Refreshing the page doesn't seem to help, or clearing my browsers cache. I have to press the refresh button under the message 
![GJrMabqtQv](https://user-images.githubusercontent.com/75234274/119894701-ec4d5000-bf0a-11eb-998b-9f04a7461fca.png)
 at least more than 10 times for it to finally load. I can't seem to replicate the issue because I very rarely get it on the streams that I never see them on. But I did notice that I get the error message at least 99% of the times on xQcoW channel. Why does this happen?

**Comment by swiftaes** [comment]
Also been getting this about every day its quite annoying and sometimes I won't even be able to watch after refreshing many times or using different browsers etc

**Comment by TheRayJohnson** [comment]
Yeah, same here.

![image](https://user-images.githubusercontent.com/36357206/120523239-962a5200-c3cd-11eb-9a7a-1155132f4d0c.png)

**Comment by Twizzer** [comment]
same

**Comment by PurpleHerby** [comment]
to be fair, I've seen this without the extension loaded, so not sure if it's genuinely a network error on their side or if it's made worse by the extension. Also seen it happen when a streamer was trying to watch another stream, they also did not have the extension loaded that I could see. Not trying to dismiss it as a potential issue, just pointing out it happens.

**Comment by swiftaes** [comment]
> to be fair, I've seen this without the extension loaded, so not sure if it's genuinely a network error on their side or if it's made worse by the extension. Also seen it happen when a streamer was trying to watch another stream, they also did not have the extension loaded that I could see. Not trying to dismiss it as a potential issue, just pointing out it happens.

All I know is it works fine when I turn the addon off and with the addon on I get this constantly sometimes taking 5 mins to go away eventually.

**Comment by oxsi91** [comment]
is it stop working now?

**Comment by cnkeats** [comment]
Unfortunately it looks like network error #2000 is back

**Comment by oxsi91** [comment]
it show error 
this line color yellow in the error log
`    req.open("GET", `https://api.ttv.lol/ping`, false);`
