### ISSUE TITLE
Extension stopped working

### ISSUE THREAD

**Issue by c133** [TTV-LOL/extensions#14]
Hi captainswain, first of all thank you so much for this extension, it's genuinely improved my quality of life. It brings happiness to my daily life. I hope you will never succumb to legal threats from Twitch.

I've noticed today that the extension has stopped working. Usually when I get the black screen / network error it can be resolved by refreshing a few times. But now even after refreshing, it stays black, and stream never loads. Hope you will be able to fix this, and thanks for your time. If it matters I am using the google extension on microsoft edge chromium browser.

**Comment by captainswain** [comment]
Hi,

This should be fixed now. I apologize, I added back a server into rotation that crashed and wasn't removed from the loadbalancer. So if you were hitting that specific server you would experience streams loading indefinitely.

it has now been removed, so you should be good to go!
