### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by Sqwrly** [TTV-LOL/extensions#15]
Hello. Love this extension but it seems to have stopped working today. I'm on FF and my friend is on Chrome, both having issues seeing ads. Thanks for the hard work.

**Comment by hiddenyak** [comment]
Chrome user. Also stopped working in the last 8 hours for me.

**Comment by c133** [comment]
I am seeing ads as well today

**Comment by Picticon** [comment]
Could not see any stream, was getting error 2000 under Chrome. Had to disable extension.

**Comment by Vxngeance** [comment]
I was getting the network error thing on version 0.0.4.
