### ISSUE TITLE
Buffer size greatly reduced/buffering often

### ISSUE THREAD

**Issue by blunttheking** [TTV-LOL/extensions#16]
I noticed that lately my Twitch streams were buffering a lot more often on 1080 60 quality, despite every other website seeming normal, so opened the advanced video stats on Twitch and noticed that the buffer size of the stream was very low, hovering around 1-1.5 seconds if not constantly buffering. Of course, using lower qualities helped stabilize this. After disabling TTV-LOL however, the buffer size for 1080 60 shot back up to normal, 4ish seconds in my case.

I'm no developer, or web designer, so I dunno if this is something twitch changed overall recently, or a direct thing to stop TTV-LOL, but it'd probably be a good idea to look into it in case they're about to do something to really hinder it.

**Comment by AlyoshaVasilieva** [comment]
If you open the Twitch player settings (gear icon), and set Low Latency to off in Advanced, does this fix it?

Buffer size of 1-2 seconds is normal for low latency mode.

**Comment by blunttheking** [comment]
Ah. Sorry. I hadn't thought to check that, I forgot low latency mode was a thing. Sorry for the trouble, I bet that's all this is.

**Comment by blunttheking** [comment]
Actually no, I take that back. I still think something is up. Regardless of the buffer size, I'm still getting a lot of buffering on streams at 1080 60, with or without low latency, until I disable the extension. When I do, streams play normally with no buffering at all at 1080 60. There's still something about the extension that is causing a lot of buffering. I just at this point don't know if it's something to do with my system, the extension, or twitch, and I don't have the knowledge to troubleshoot that alone.

**Comment by captainswain** [comment]
We have fixed the bug that forced on low latency mode. Let us know if you are still experiencing the buffering, it should hopefully be fixed.

**Comment by blunttheking** [comment]
I'm not sure if there's something I need to do on my end to update to have the fix, but I'm still having the problem. I even tried toggling it off and on mid-stream and it always performs better turned off, 100% of the time across all streams.

If it matters I did also try completely removing and redownloading the extension, no change.

**Comment by fireflymagic** [comment]
An issue that seems to be caused by this change is that you now cannot put low latency mode on at all.
