### ISSUE TITLE
Why is the extension code different to the GitHub repo?

### ISSUE THREAD

**Issue by InterestingTime** [TTV-LOL/extensions#18]
Why is the extension code different to the code on here? I have tried chrome and firefox but both say last updated april. I looked at the code from the downloaded firefox addon and its different. Mainly it doesnt fix the userID/IP leak. Its a bit misleading to show a github link that has different code to the actual extension.

**Comment by captainswain** [comment]
Hi,

The code simply hasn't been submitted yet as were working on a UI overhaul.
