### ISSUE TITLE
[Feature Request] Firefox Support

### ISSUE THREAD

**Issue by ProZBoy** [TTV-LOL/extensions#2]
Any plan on adding firefox support?

**Comment by ehl0el** [comment]
^ would love to see a port to firefox! :)

**Comment by Blackdima4** [comment]
+1 for Firefox support. Fuck these Twitch ads.

**Comment by amethystau** [comment]
you can add it to firefox in debug mode if your desperate

**Comment by PsycloneTM** [comment]
> 
> 
> you can add it to firefox in debug mode if your desperate

Video please

**Comment by captainswain** [comment]
Hey, guys just got the firefox plugin submitted and the code pushed to this repository.

Should be going live  @ https://addons.mozilla.org/en-US/firefox/addon/ttv-lol/ once it's approved.

Cheers!

**Comment by PsycloneTM** [comment]
> Should be going live @ https://addons.mozilla.org/en-US/firefox/addon/ttv-lol/ once it's approved.


Make sure to add it to your website
