### ISSUE TITLE
Does not block midrolls

### ISSUE THREAD

**Issue by Bilge** [TTV-LOL/extensions#26]
Although this does block prerolls, it does not mitigate midrolls (manually initiated ads) at all. Moreover, it does not actually block prerolls, either, unless the host page has just loaded. That is, if the player has been loaded but paused for some time, resuming the player will not block the incoming preroll either.

**Comment by abdulsalam0** [comment]
This is not a solution but if you are getting midroll ads you can refresh the page and it will skip them for you. midrolls can be really annoying if they place 5-7 ads in a row.
