### ISSUE TITLE
Twitch gives  error #2000 when using the  extension.

### ISSUE THREAD

**Issue by ElAtiendeBoludos** [TTV-LOL/extensions#27]
As of today 25/10/2021 the  extension is not working.  It causes twitch to give the error. #2000. Disabling the extension fixes this error.

**Comment by floppacrisp** [comment]
this seems to have started happening for me just now as well

**Comment by Illidan1943** [comment]
Yeah, Twitch is completely unusable with this extension now

**Comment by AutomaticFailure** [comment]
Starting today, this is happening again. Seems Twitch updated their API according to a Reddit post.
