### ISSUE TITLE
TTV.LOL users don't count as viewers

### ISSUE THREAD

**Issue by Adamcake** [TTV-LOL/extensions#28]
When using TTV.LOL my viewership does not count towards the stream's viewer count. When I disable the extension, it starts counting me.

We recently learned that Twitch applies trust scores to IP ASN groups when calculating the viewer count as a way of combating viewbotting, so I expect this issue happens because my viewership from Twitch's point of view is coming from your network and not my own IP address. It's not a very pleasant trade-off; I feel bad seeing my friends have four people chatting and yet only one viewer because we're all using this extension to block ads.

Is there any easy solution to this? I don't know much about your extension's internals but I wonder if there's some way of having my browser load a direct 160p stream and hiding and muting it. This way I'd count as a viewer and the streamer would get ad revenue as well.

**Comment by eocow** [comment]
Not an expert but you can self host this I believe self hosting is the best way to solve this. I believe it is a goal in the future to have the server side code public and ready to setup.

**Comment by Adamcake** [comment]
That would be nice and I'd definitely do that if it were an option. However, most users will probably not bother to do that or have the technical skills necessary to do it, so I don't think it would solve the problem outright.
