### ISSUE TITLE
No buffering with extension off, buffering with it on

### ISSUE THREAD

**Issue by checkraisefold** [TTV-LOL/extensions#29]
I only have 20 ms latency to ttv.lol and no packet loss after running a traceroute. I don't understand why/how I have buffering every 2 seconds. Using latest Chrome. Additionally, I have 1gbps internet
My friend with about 50 ms latency to ttv.lol experiences no buffering with the extension enabled.

**Comment by checkraisefold** [comment]
After testing in incognito mode, this persists even with only this extension and ublock origin enabled.

**Comment by pixeltris** [comment]
The issue relates to how Twitch handles their routing. Only the initial m3u8 request goes through the proxy. Afterwards Twitch picks a server closest to the proxy location to handle all stream traffic.

Really Twitch shouldn't have any issues pumping high quality streams from anywhere to anywhere. But I guess there's some complex routing stuff going on and that isn't the case.

No real fix unfortunately.

Ref https://github.com/TTV-LOL/extensions/issues/17

**Comment by checkraisefold** [comment]
> The issue relates to how Twitch handles their routing. Only the initial m3u8 request goes through the proxy. Afterwards Twitch picks a server closest to the proxy location to handle all stream traffic.
> 
> Really Twitch shouldn't have any issues pumping high quality streams from anywhere to anywhere. But I guess there's some complex routing stuff going on and that isn't the case.
> 
> No real fix unfortunately.
> 
> Ref #17

That would be it; sticking to a lower quality and keeping low latency mode off seems to eliminate most buffering issues. Randomly, 1080p will work for 30 minutes then no matter how much I refresh the page buffering continues. After switching to 720 + low latency off, issue does not persist.
