### ISSUE TITLE
Ads starting to show

### ISSUE THREAD

**Issue by madmossy** [TTV-LOL/extensions#3]
Started to get ads on twitch.tv in the UK, they started appearing today around 3 hours ago.

**Comment by captainswain** [comment]
We just pushed a hotfix to our API. Keep us updated if you are still receiving these ads :)

**Comment by paufase** [comment]
I'm receiving ads now

**Comment by placchio** [comment]
Im also getting ads (although, so far it seems im only getting the ones that the streamers run)

**Comment by Velegand** [comment]
Just got a midroll ad

**Comment by pat22296** [comment]
Seems to be the case for me as well. Refreshing the page makes the ads disappear again.

**Comment by NovaMoon** [comment]
i seem to be getting german ads now
