### ISSUE TITLE
Ads appear on subscribed channels

### ISSUE THREAD

**Issue by Anthony6996** [TTV-LOL/extensions#30]
Although the extension does block the ads that appear when you first go into a new stream, it also makes ads appear on channels you are subscribed which is incredibly annoying. Although this can be solved by pressing F5, I can't be asked to alt+tab every 10 minutes to skip them. Could this please be fixed?

**Comment by Volatar** [comment]
I can confirm this is happening.

**Comment by ElSabroso** [comment]
this is still happening now to me on the chrome extension
![image](https://user-images.githubusercontent.com/22121997/183099214-93e8d000-6be0-4113-9371-a6d649c78dfe.png)
