### ISSUE TITLE
Not working (Error #2000)

### ISSUE THREAD

**Issue by ShadyDeth** [TTV-LOL/extensions#32]
As of today it completely stopped working. (Error #2000)

Guessing is server side @captainswain

**Comment by Nintendo32** [comment]
Getting the same error (#2000) on my end.

**Comment by Zevgor** [comment]
Yep, this just started happening this evening for me as well. I'm assuming Twitch is doing something with ads again.

**Comment by Zevgor** [comment]
Has resumed working as of 12/17 at 8:47AM for me.
