### ISSUE TITLE
Getting midrolls again

### ISSUE THREAD

**Issue by Borinius** [TTV-LOL/extensions#37]
I'm getting midrolls on latest firefox and via the xtra twitch android app. Anyone else? (both using ttv-lol).

**Comment by younesaassila** [comment]
Same here on Firefox 98.0.2, TTV LOL 0.0.0.5

**Comment by etshy** [comment]
Same problem with chrome 100.0.4896.75
I sometimes have midroll that put the stream above chat and ads on the "big screen"
