### ISSUE TITLE
Firefox extension page not working

### ISSUE THREAD

**Issue by finiteLimit** [TTV-LOL/extensions#4]
I am unable to install the extension on Firefox. The extension page (listed in the README file of this Github), links to a dead page stating the extension is not found.

**Comment by captainswain** [comment]
Hi, the plugin is currently awaiting the approval process. 

Once it is approved you will be able to access it through the link in the readme. If you want to use the plugin now you can follow this process https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Your_first_WebExtension#installing using the folder inside this repo.

~ swain

**Comment by captainswain** [comment]
I have uploaded the official xpi file here:

[ttv_lol-0.0.0.3-fx.xpi.zip](https://github.com/TTV-LOL/extensions/files/6330359/ttv_lol-0.0.0.3-fx.xpi.zip)

Not sure if you can install it directly this way

**Comment by Blackdima4** [comment]
Thanks for taking the time to implement Firefox support.
