### ISSUE TITLE
All Twitch streams are prevented from loading (even if subbed to streamer or Twitch Turbo)

### ISSUE THREAD

**Issue by DoraTheExploder** [TTV-LOL/extensions#42]
As of approximately 3:00PM PST on 08/18 (time of posting) all Twitch streams have been prevented from loading if the extension is enabled. I am using Firefox 103.0.2 (64-bit) for Windows (10). I have also been told the issue is occurring on Chromium-based browsers as well, but have not tested it myself.

**Comment by TBirdSoars** [comment]
This happened to me as well, but the extension started working again soon after. Now, it just doesn't work, see #43

**Comment by Skuzee** [comment]
This plugin appeared to work fine for me until today, now I'm getting ads again. I presume I'm not the only one. The videos are loading fine, just getting ads.

**Comment by modernpicasso** [comment]
Same. I noticed it stopped working today.
