### ISSUE TITLE
Getting Midrolls 

### ISSUE THREAD

**Issue by Moonchill** [TTV-LOL/extensions#45]
Been watching a few streams again and I'm getting midrolls. Not much else to contribute. Let me know if you need more info.

Edit: It just happened on a stream I'm subscribed to. . .

**Comment by RSKcsgo** [comment]
True, and now I'm getting "There was a network error. Please try again. (Error #2000)"

**Comment by TsukiZero** [comment]
Yes, this extension doesn't work completely. It still bleeds.
