### ISSUE TITLE
API is down

### ISSUE THREAD

**Issue by AndreDK7** [TTV-LOL/extensions#46]
api.ttv.lol is giving error 521 and due to that the adblock is not working

**Comment by cookie-monster-bit** [comment]
If only they open sourced the api part. There could be bunch of mirrors, etc.

**Comment by nucombo** [comment]
> If only they open sourced the api part. There could be bunch of mirrors, etc.

then twitch could crack it much easier and permanently

**Comment by okseb** [comment]
Can confirm it hasn't been working since yesterday.

**Comment by gustavoab2** [comment]
api is up again
