### ISSUE TITLE
Firefox Extension got taken off the the store but I luckily downloaded it before it was taken off and its working great!

### ISSUE THREAD

**Issue by PsycloneTM** [TTV-LOL/extensions#5]
![ttv](https://i.imgur.com/KmgCpGy.png)

**Comment by finiteLimit** [comment]
Anyone know why it was taken down?

**Comment by sean8102** [comment]
> Anyone know why it was taken down?

Wouldn't be surprised if Twitch/Amazon filed a complaint of some kind to get it taken down. Maybe only a matter of time for the Chrome version. They have been VERY serious about stopping ad blocking on their site for a few months now.

**Comment by captainswain** [comment]
Hi there,

The reason it was taken down was synchronous web requests being made. I have submitted a fix to firefox and they are currently reviewing it. Hopefully, it will be up soon :crossed_fingers: !

**Comment by PsycloneTM** [comment]
> 
> 
> Hi there,
> 
> The reason it was taken down was synchronous web requests being made. I have submitted a fix to firefox and they are currently reviewing it. Hopefully, it will be up soon 🤞 !

It has been approved make sure to upload it to your website now

**Comment by CycIoneTM** [comment]
Welp it looks like Firefox really doesn't like your extension
