### ISSUE TITLE
Unable to use Picture in Picture mode when using TTV-LOL on Firefox

### ISSUE THREAD

**Issue by QuickStick123** [TTV-LOL/extensions#57]
![image](https://user-images.githubusercontent.com/31533893/212629207-6047d660-7fa8-4504-a19c-bdba032e8232.png)

This button brings the video element into a movable window that you can resize. Your extension breaks this as clicking the button does nothing.

**Comment by ghost** [comment]
You cannot use PiP mode at ALL unless you're subscribed. Twitch breaks this without any addons.
