### ISSUE TITLE
2000 Network error

### ISSUE THREAD

**Issue by pat22296** [TTV-LOL/extensions#7]
Since today I'm getting the 2000 Network error every time I load a stream on Firefox. After disabling the addon everything works fine.

**Comment by SaltyLiquorice** [comment]
Same here on Chrome.

**Comment by CodyMKW** [comment]
same on chrome for me  just started not that long ago

**Comment by bamtan** [comment]
Use Purple AdBlock for the timebeing (no conflict having both enabled)
Link is in here https://github.com/pixeltris/TwitchAdSolutions

**Comment by lufranco** [comment]
Same happening to me on chrome

**Comment by pat22296** [comment]
Issue seems to be resolved again, thanks for the fast action.
